# Generated by Django 4.2.7 on 2023-11-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_alter_article_author_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
